### ISSUE TITLE
Why asyncio?

### ISSUE THREAD

**Issue by JungleTryne** [Animatea/tense#1]
Hey! I stumbeled across your project, it's very well organized and fancy, you definitely deserved a star! I've got a question though.

Why does your project require asyncio runtime? It seems to me that your code doesn't have any kind of blocking code nor does it heavy computations. And, from my perspective, async code makes it just harder to grasp and adds more complex structures, like LRU cache for async functions, that you could've used from functools if your code was synchronious.

**Comment by Animatea** [comment]
> Hey! I stumbeled across your project, it's very well organized and fancy, you definitely deserved a star! I've got a question though.
> 
> Why does your project require asyncio runtime? It seems to me that your code doesn't have any kind of blocking code nor does it heavy computations. And, from my perspective, async code makes it just harder to grasp and adds more complex structures, like LRU cache for async functions, that you could've used from functools if your code was synchronious.

Thanks for the question, I really thought about async of project. In the near future, most likely the project will be slightly changed.
